import { 
    CATEGORY_GET_CATEGORIES,
    CATEGORY_CREATE_CATEGORY,
    CATEGORY_DELETE_CATEGORY,
    CATEGORY_GET_CATEGORY,
    CATEGORY_UPDATE_CATEGORY
 } from '../../../modules/Category/endpoints.js';

 import { 
    TAG_CREATE_TAG,
    TAG_DELETE_TAG,
    TAG_GET_ADVERTISMENTS_TAG,
    TAG_GET_TAG,
    TAG_GET_TAGS,
    TAG_UPDATE_TAG 
 } from '../../../modules/Tags/endpoint.js';
 import { 
    ADVERTISMENT_CREATE_AD,
    ADVERTISMENT_DELETE_AD,
    ADVERTISMENT_GET_AD,
    ADVERTISMENT_GET_ADS,
    ADVERTISMENT_GET_ADS_BY_CATEGORY, 
    ADVERTISMENT_GET_ADVERTISER_ADS_,
    ADVERTISMENT_UPDATE_AD

    } from '../../../modules/Advertisement/endpoints.js';

export default [
    CATEGORY_GET_CATEGORIES,
    CATEGORY_CREATE_CATEGORY,
    CATEGORY_DELETE_CATEGORY,
    CATEGORY_GET_CATEGORY,
    CATEGORY_UPDATE_CATEGORY,
    TAG_CREATE_TAG,
    TAG_DELETE_TAG,
    TAG_GET_ADVERTISMENTS_TAG,
    TAG_GET_TAG,
    TAG_GET_TAGS,
    TAG_UPDATE_TAG ,
    ADVERTISMENT_CREATE_AD,
    ADVERTISMENT_DELETE_AD,
    ADVERTISMENT_GET_AD,
    ADVERTISMENT_GET_ADS,
    ADVERTISMENT_GET_ADS_BY_CATEGORY, 
    ADVERTISMENT_GET_ADVERTISER_ADS_,
    ADVERTISMENT_UPDATE_AD
];
